import type { LLMComparison, ComparisonGroup } from '@/types';

/**
 * Sample LLM comparisons for a Button component
 * These demonstrate different LLM providers generating similar functionality
 */
export const buttonComparisons: LLMComparison[] = [
  {
    id: 'gpt4-button',
    title: 'GPT-4 Button',
    prompt: 'Create a modern, accessible button component in React with primary styling, hover effects, and click handling.',
    sourceCode: `function Button({ children, onClick }) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: '12px 24px',
        fontSize: '16px',
        fontWeight: '600',
        color: '#ffffff',
        backgroundColor: '#2563eb',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.backgroundColor = '#1d4ed8';
        e.currentTarget.style.transform = 'translateY(-1px)';
        e.currentTarget.style.boxShadow = '0 4px 8px rgba(0, 0, 0, 0.15)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.backgroundColor = '#2563eb';
        e.currentTarget.style.transform = 'translateY(0)';
        e.currentTarget.style.boxShadow = '0 2px 4px rgba(0, 0, 0, 0.1)';
      }}
    >
      {children}
    </button>
  );
}`,
    tokens: 245,
    llmProvider: 'GPT-4',
  },
  {
    id: 'claude-button',
    title: 'Claude Button',
    prompt: 'Create a modern, accessible button component in React with primary styling, hover effects, and click handling.',
    sourceCode: `function Button({ children, onClick }) {
  const buttonStyle = {
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: 'bold',
    color: 'white',
    backgroundColor: '#0ea5e9',
    border: '2px solid transparent',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background-color 0.3s, border-color 0.3s',
    outline: 'none',
  };

  const handleMouseOver = (e) => {
    e.target.style.backgroundColor = '#0284c7';
    e.target.style.borderColor = '#0369a1';
  };

  const handleMouseOut = (e) => {
    e.target.style.backgroundColor = '#0ea5e9';
    e.target.style.borderColor = 'transparent';
  };

  return (
    <button
      style={buttonStyle}
      onClick={onClick}
      onMouseOver={handleMouseOver}
      onMouseOut={handleMouseOut}
      aria-label="Primary action button"
    >
      {children}
    </button>
  );
}`,
    tokens: 198,
    llmProvider: 'Claude',
  },
  {
    id: 'gemini-button',
    title: 'Gemini Button',
    prompt: 'Create a modern, accessible button component in React with primary styling, hover effects, and click handling.',
    sourceCode: `function Button({ children, onClick }) {
  const [isHovered, setIsHovered] = React.useState(false);

  const baseStyle = {
    padding: '11px 22px',
    fontSize: '15px',
    fontWeight: '500',
    color: '#fff',
    backgroundColor: isHovered ? '#7c3aed' : '#8b5cf6',
    border: 'none',
    borderRadius: '7px',
    cursor: 'pointer',
    transition: 'background-color 0.25s ease-in-out',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  };

  return (
    <button
      style={baseStyle}
      onClick={onClick}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      role="button"
      tabIndex={0}
    >
      {children}
    </button>
  );
}`,
    tokens: 223,
    llmProvider: 'Gemini',
  },
];

/**
 * Sample comparison group for Button component demonstrations
 */
export const buttonComparisonGroup: ComparisonGroup = {
  id: 'button-comparison',
  componentName: 'Button',
  description:
    'A comparison of button components generated by different LLM providers. Each was given the same prompt to create a modern, accessible button with styling and interactions.',
  comparisons: buttonComparisons,
};
